---
title: "COVID Musings"
author: "Andres de Loera-Brust"
date: "April 27, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(readr)
library(readxl)
library(janitor)
library(tidyverse)
library(ggthemes)

```

```{r download}

#Covid Data

county_covid <- read_csv("https://s3-us-west-1.amazonaws.com/starschema.covid/NYT_US_COVID19.csv") %>%
  
  clean_names() %>%
  
  filter(last_reported_flag == TRUE) %>%
  
  mutate(fips = as.character(fips),
         fips = str_pad(fips, 5, pad= "0")) %>%
  
  select(state, county, fips, covid_cases = cases, covid_deaths = deaths, date)

#ACO Data

download.file(url = "https://www.cms.gov/Research-Statistics-Data-and-Systems/Downloadable-Public-Use-Files/SSPACO/Downloads/ACOSSPCOUNTYASSIGNEDPUF2017.zip",
              dest = "aco_county_2017puf.zip",
              mode = "wb")

unzip("aco_county_2017puf.zip")

county_aco <- read_csv("ACO.SSP.COUNTY.ASSIGNED.PUF.2017.csv") %>%
  
  clean_names() %>%
  
  mutate(total_benes = as.numeric(tot_ab),
         total_benes = replace_na(total_benes, 0),
         state_id = str_pad(state_id, 2, pad = "0"),
         county_id = str_pad(county_id, 3, pad = "0"),
         state_county_ssa = paste(state_id, county_id, sep = "")) %>%
  
  select(aco_num = aco_id, state = state_name, county = county_name, state_county_ssa, total_benes) %>%
  
  group_by(state, county, state_county_ssa) %>%
  
  summarize(aco_beneficiaries = sum(total_benes))


#Medicare Data

download.file(url = "https://downloads.cms.gov/files/State-County-All-Table-2017.zip",
              dest = "medicare_spending.zip",
              mode = "wb")

unzip("medicare_spending.zip")

county_ffsma <- read_excel("State County All Table 2017.xlsx", 
    sheet = "State_county 2017", skip = 1) %>%

  clean_names() %>%
  
  select(state, county, state_and_county_fips_code, beneficiaries_with_part_a_and_part_b, ffs_beneficiaries, ma_beneficiaries) %>%

  mutate(ffs_beneficiaries = as.numeric(ffs_beneficiaries),
         ffs_beneficiaries = replace_na(ffs_beneficiaries, 0),
         beneficiaries_with_part_a_and_part_b = as.numeric(beneficiaries_with_part_a_and_part_b),
         beneficiaries_with_part_a_and_part_b = replace_na(beneficiaries_with_part_a_and_part_b, 0),
         ma_beneficiaries = as.numeric(ma_beneficiaries),
         ma_beneficiaries = replace_na(ma_beneficiaries, 0),
         state_and_county_fips_code = as.character(state_and_county_fips_code),
         state_and_county_fips_code = str_pad(state_and_county_fips_code, 5, pad= "0"),
         state = state.name[match(state,state.abb)]) %>%
  
  filter(!is.na(state_and_county_fips_code))

#County Code Crosswalk

download.file(url = "https://www.nber.org/ssa-fips-state-county-crosswalk/2017/ssa_fips_state_county2017.zip",
              dest = "county_crosswalk2017.zip",
              mode = "wb")

unzip("county_crosswalk2017.zip")

county_crosswalk <- read_xlsx("FY 2017 FR Cty CBSA Xwalk and CBSA Con Cty.xlsx") %>%
  
  clean_names() %>%
  
  select(state, county, ssa_state_county_code, fips_state_county_code)

#County Populations 

county_pop <- read_csv("https://www2.census.gov/programs-surveys/popest/datasets/2010-2019/counties/totals/co-est2019-alldata.csv") %>%
  
  clean_names() %>%
  
  mutate(fips = paste(state, county, sep = "")) %>%
    
  select(fips, population = popestimate2019)


#ICU Beds

county_icu <- read_csv("https://s3-us-west-1.amazonaws.com/starschema.covid/KFF_US_ICU_BEDS.csv") %>%
  clean_names() %>%
  
  mutate(fips = as.character(fips),
         fips = str_pad(fips, 5, pad= "0")) %>%
  
  select(state, county, fips, hospitals, icu_beds)

#Employment stats

download.file(url = "https://www.bls.gov/web/metro/laucntycur14.zip",
              dest = "countyemploystats.zip",
              mode = "wb")

unzip("countyemploystats.zip")

county_ue_rate <- read_excel("laucntycur14.xlsx", 
    skip = 4) %>%
  clean_names() %>%
  filter(!is.na(code_2), code_2 != "72") %>%
  mutate(fips = paste(code_2, code_3, sep = "")) %>%
  select(fips, name = county_name_state_abbreviation, period, unemployment_rate = percent)%>%
  filter(period %in% c("Jan-20", "Mar-20 p")) %>%
  spread(key = period, value = unemployment_rate) %>%
  mutate(ur_change = `Mar-20 p`-`Jan-20`) %>%
  rename(mar_ur = `Mar-20 p`, jan_ur = `Jan-20`)

county_unemployment <- read_excel("laucntycur14.xlsx", 
    skip = 4) %>%
  clean_names() %>%
  filter(!is.na(code_2), code_2 != "72") %>%
  mutate(fips = paste(code_2, code_3, sep = "")) %>%
  select(fips, name = county_name_state_abbreviation, period, unemployed) %>%
  filter(period %in% c("Jan-20", "Mar-20 p")) %>%
  spread(key = period, value = unemployed) %>%
  mutate(ue_change = `Mar-20 p`-`Jan-20`) %>%
  rename(mar_ue = `Mar-20 p`, jan_ue = `Jan-20`)

county_employment <- read_excel("laucntycur14.xlsx", 
    skip = 4) %>%
  clean_names() %>%
  filter(!is.na(code_2), code_2 != "72") %>%
  mutate(fips = paste(code_2, code_3, sep = "")) %>%
  select(fips, name = county_name_state_abbreviation, period, employed) %>%
  filter(period %in% c("Jan-20", "Mar-20 p")) %>%
  spread(key = period, value = employed) %>%
  mutate(em_change = `Mar-20 p`-`Jan-20`) %>%
  rename(mar_em = `Mar-20 p`, jan_em = `Jan-20`) %>%
  left_join(county_ue_rate, by = c("fips", "name")) %>%
  left_join(county_unemployment, by = c("fips", "name"))

rm(county_ue_rate, county_unemployment)
  

```

```{r merging}

county_master <- county_crosswalk %>%
  
  full_join(county_ffsma, by = c("fips_state_county_code" = "state_and_county_fips_code")) %>%
  full_join(county_aco, by = c("ssa_state_county_code" = "state_county_ssa")) %>%
  
  mutate(aco_beneficiaries = replace_na(aco_beneficiaries, 0),
         aco_participation_rate = aco_beneficiaries/(ffs_beneficiaries+ma_beneficiaries),
         ma_participation_rate = ma_beneficiaries/(ffs_beneficiaries+ma_beneficiaries),
         non_ma_aco_rate = (ffs_beneficiaries - aco_beneficiaries)/(ffs_beneficiaries + ma_beneficiaries ),
         rate_check = aco_participation_rate + ma_participation_rate + non_ma_aco_rate) %>%
  
  filter(state != "PR") %>%
  
  select(state, county, fips_state_county_code, ssa_state_county_code, beneficiaries_with_part_a_and_part_b, ffs_beneficiaries, ma_beneficiaries, aco_beneficiaries, ma_participation_rate, aco_participation_rate, non_ma_aco_rate) %>%
  
  full_join(county_covid, by = c("fips_state_county_code" = "fips", "state", "county")) %>%
  full_join(county_pop, by = c("fips_state_county_code" = "fips")) %>%
  full_join(county_icu, by = c("fips_state_county_code" = "fips", "state", "county")) %>%
  
  mutate(covid_case_rate = covid_cases/population) %>%
  
  full_join(county_employment, by = c("fips_state_county_code" = "fips"))


```


```{r analysis}

county_master %>%
  ggplot(aes(x = aco_participation_rate, y = covid_case_rate)) +
  geom_point(alpha = 0.33) +
  geom_smooth(method = "lm") + 
  scale_y_continuous() +
  labs(title = "Relationship Between ACO Participation Rate and COVID-19 Case Rate",
       x = "ACO Participation Rate",
       y = "COVID-19 Case Rate",
       caption = "Source: NYT, CMS, Census Bureau")

covid_reg <- lm(covid_case_rate ~ aco_participation_rate, data = county_master)

summary(covid_reg)


county_master %>%
  ggplot(aes(x = aco_participation_rate, y = ur_change)) +
  geom_point(alpha = 0.33) +
  geom_smooth(method = "lm") +
  labs(title = "",
       x = "ACO Participation Rate",
       y = "Change in Unemployment Rate (Mar 2020 - Jan 2020)",
       caption = "Source: CMS, BLS")

ur_reg <- lm(ur_change ~ aco_participation_rate, data = county_master)

summary(ur_reg)


county_master %>%
  ggplot(aes(x = covid_case_rate, y = ur_change)) +
  geom_point(alpha = 0.2) +
  geom_smooth(method = "lm") +
  labs(title = "",
       x = "COVID-19 Case Rate",
       y = "Chang in Unemployment Rate")

```


```{r export}

write_csv(county_master, "county_covid_cms_musings.csv")

```

